version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /web
    cooldown:
      default-days: 3
    schedule:
      interval: daily
    versioning-strategy: increase
    groups:
      tanstack:
        patterns:
          - "@tanstack/*"
      eslint:
        patterns:
          - "*eslint*"
      vite:
        patterns:
          - "*vite*"
      chakra:
        patterns:
          - "@chakra-ui/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      testing-library:
        patterns:
          - "@testing-library/*"
          - "*jsdom*"

