### Index redirects
GET http://localhost:8080/


### Robots.txt
GET http://localhost:8080/robots.txt


### Metrics
GET http://localhost:8080/metrics


### Healthcheck
GET http://localhost:8080/healthz


### Mobile config
GET http://localhost:8080/.mobileconfig


### Reload blocklist
POST http://admin.localhost:8080/api/reload
User-Agent: test-client

### Check blocklist (JSON)
POST http://admin.localhost:8080/api/check
Content-Type: application/json

["google.com", "www.ex.co", "ads.net"]

### Check blocklist (Plain text)
POST http://admin.localhost:8080/api/check
Content-Type: text/plain

google.com
www.ex.co
ads.net

### DoH POST
POST http://localhost:8080/dns-query
Content-Type: application/dns-message
Accept: application/dns-message

< ./docs/query.bin

### DoH GET
GET http://localhost:8080/dns-query?dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB
Accept: application/dns-message


### Admin UI
GET http://admin.localhost:8080/
Accept: text/html


### Who Am I
GET http://admin.localhost:8080/api/whoami
Accept: application/json


### DNS Events Stream (SSE)
GET http://admin.localhost:8080/api/events
Accept: text/event-stream
