### Index redirects
GET http://localhost:8080/


### Robots.txt
GET http://localhost:8080/robots.txt


### ACME challenge
GET http://localhost:8080/.well-known/acme-challenge/abc123XYZ


### Metrics
GET http://localhost:8080/metrics


### Healthcheck
GET http://localhost:8080/healthz


### Mobile config
GET http://localhost:8080/.mobileconfig


### Reload blocklist
GET http://localhost:8080/reload
User-Agent: test-client

### Check blocklist (JSON)
POST http://localhost:8080/check
Content-Type: application/json

["google.com", "blocked.com", "ads.net"]

### Check blocklist (Plain text)
POST http://localhost:8080/check
Content-Type: text/plain

google.com
blocked.com
ads.net
